#!/bin/sh

# Create signed release tarballs and signature files from current svn.
# Since you don't have my gpg key, this doesn't do you much good,
# but if I get hit by a bus the next maintainer might find this useful.
# Run this in an empty directory.  The VERSION= line can get confused
# otherwise.

#svn co svn://.net/trunk/
cd  || { echo "cd  failed"; exit 1; }
make release || { echo "make release failed"; exit 1; }
cd ..

VERSION=`ls -*.tar.gz | sed 's/-\(.*\)\.tar\.gz/\1/'`

zcat -$VERSION.tar.gz | bzip2 > -$VERSION.tar.bz2

test -f -$VERSION.tar.gz || { echo "no -$VERSION.tar.gz"; exit 1; }
test -f -$VERSION.tar.bz2 || { echo "no -$VERSION.tar.bz2"; exit 1; }

signit()
{
echo "$1 released `date -r $1 -R`

MD5:  `md5sum $1`
SHA1: `sha1sum $1`

To verify this signature, you can obtain my public key
from http://.net/~vda/vda_pubkey.gpg
" | gpg --clearsign > "$1.sign"
}

signit -$VERSION.tar.gz
signit -$VERSION.tar.bz2
