#!/bin/sh

=../

i=4000
echo "Before we started $i copies of '$ sleep 10':"
$ nmeter '%t %[pn] %m' | head -3

while test $i != 0; do
    $ sleep 10 &
    i=$((i-1))
done
sleep 1

echo "After:"
$ nmeter '%t %[pn] %m' | head -3
